name: Build docs
on:
  push:
    branches: [release, main]
  pull_request:
    branches: [release, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven

      - name: Build docs
        run: mvn javadoc:javadoc

      - name: Tidy up the javadocs
        id: tidy
        uses: cicirello/javadoc-cleanup@v1
        with:
          path-to-root: target/site/apidocs

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: docs
          folder: target/site/apidocs